Use manual encoders for circe
This works around the following compilation error, which was occurring
when using auto derivation:

[error] -- Error: /home/darius/dev/synonyms/src/test/scala/synonyms/http/routes/SynonymsRoutesSuite.scala:76:25
[error]  76 |            result.asJson
[error]     |                         ^
[error]     |           method derived is declared as `inline`, but was not inlined
[error]     |
[error]     |           Try increasing `-Xmax-inlines` above 32
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from package.scala:47